---

- hosts: all
  become: true
  tasks:
  
  - name: update OS and install apache and php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: update OS and install apache and php packages for CentOS
    dnf:
      name:
        - httpd
        - php
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
