- name: install mariadb server package (CentOS)
  tags: centos,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb server (Ubuntu)
  tags: ubuntu,mariadb,db
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
